# Generated by Django 4.2.7 on 2024-01-24 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautycityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=200, verbose_name='Адрес студии')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото студии')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='beautycityapp.studio'),
        ),
    ]
