# Generated by Django 4.2.7 on 2024-01-24 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautycityapp', '0006_alter_client_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Комментарий к заказу')),
                ('promocode', models.CharField(blank=True, max_length=20, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Итоговая цена')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='beautycityapp.client')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='beautycityapp.service')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='beautycityapp.slot')),
            ],
        ),
    ]
