# Generated by Django 4.2.7 on 2024-01-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautycityapp', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Сумма оплаты')),
                ('tips', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Чаевые')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='beautycityapp.order')),
            ],
        ),
    ]
