# Generated by Django 4.2.7 on 2024-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycityapp', '0009_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
    ]
