# Generated by Django 4.2.7 on 2024-01-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautycityapp', '0010_alter_service_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Комментарий к заказу')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='type_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='beautycityapp.typeservice'),
        ),
    ]
