# Generated by Django 4.2.7 on 2024-01-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautycityapp', '0012_studio_title_alter_typeservice_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='addres',
            new_name='address',
        ),
    ]
