# Generated by Django 4.2.7 on 2024-01-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycityapp', '0013_rename_addres_studio_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.IntegerField(null=True, verbose_name='Стаж работы в годах'),
        ),
        migrations.AddField(
            model_name='master',
            name='profession',
            field=models.CharField(max_length=50, null=True, verbose_name='Специализация мастера'),
        ),
    ]
