# Generated by Django 4.2.7 on 2024-01-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycityapp', '0015_remove_service_master_remove_service_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='min_price',
            field=models.IntegerField(null=True, verbose_name='Минимальная цена услуги'),
        ),
    ]
