# Generated by Django 4.2.7 on 2024-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautycityapp', '0016_service_min_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='min_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(related_name='masters', to='beautycityapp.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='master',
            field=models.ManyToManyField(related_name='services', to='beautycityapp.master'),
        ),
        migrations.DeleteModel(
            name='MastersService',
        ),
    ]
